site_name: PSMilkyWay
repo_url: https://github.com/mattman-ps/PSMilkyWay
theme: readthedocs
pages:
  - Home: index.md
  - Installation and Setup:
    - Requirements: requirements.md
  - cmdlets:
    - Get-Planet: Get-Planet.md
    - Get-Moon: Get-Moon.md
  - Support: Support.md